### ISSUE TITLE
Tag already exists error using thor version:bump patch

### ISSUE THREAD

**Issue by jreslock** [RiotGamesMinions/thor-scmversion#39]
I am running thor-scmversion 1.7.0 to version my chef cookbooks and I'm having an issue where the task that bumps the version complains that the tag already exists.  

`+ thor version:bump minor
Creating and pushing tags
Tagging 0.1.0 failed due to error
Tried to tag 0.1.0, but it already exists! Either build from the latest tag at this bump level or choose a lower order bump level.`

It doesn't seem to matter what bump level I try, I receive the same error every time.  The only tag I have in the git repo is 0.0.1.

**Comment by jreslock** [comment]
This was because I didn't have global git username and email configured.  It would be helpful if thor-scmversion returned the actual scm error rather than this misleading 'tag already exists' error for all scm errors.

**Comment by jolexa** [comment]
Hello, I just spent several hours on this issue after rebuilding a jenkins instance. It would be so helpful if thor-scmversion posted the actual error.

**Comment by capoferro** [comment]
This tool is not under active development, however if you submit a pull request, I'd be happy to consider it.

**Comment by dbaggott** [comment]
@capoferro still happy to consider pull requests for this?  I'm not sure I actually have the bandwidth but wanted to make sure it would be welcomed before spending the time...
